# Spring Boot configuration
spring:
    datasource: #database accessing settings
        driver-class-name: org.h2.Driver #JDBC driver class name for H2

        #file-based H2 database
        #saved as: ./database/test_db.mv.db
        #DB_CLOSE_DELAY=-1: keep the database open for the application's lifecycle
        url: jdbc:h2:file:./database/test_db;DB_CLOSE_DELAY=-1
        username: root #username of the H2 database
        password: root@123 #password of the H2 database

    sql: #databse control settings
        init:
            mode: always #run `schema.sql` and `data.sql` scripts every time the application starts
            platform: h2 #specify the platform of these `.sql` files

    h2: # enable H2 console
        console:
            enabled: true
            path: /h2-cons #access at http://localhost:3002/h2-consoleole

    #Spring Session settings of storing user sessions in the database
    session:
        store-type: jdbc #use JDBC to store session data
        jdbc:
            initialize-schema: always #automatically create session tables(`SPRING_SESSION`, `SPRING_SESSION_ATTRIBUTES`)
            schema: classpath:org/springframework/session/jdbc/schema-h2.sql

server: #server settings
    port: 3002 #set the application runs on port 3002 (http://localhost:3002)
    error:
        include-message: always #include error messages in API responses for debugging

#application metadata
application:
    version: 0.1.0(ALPHA) #version of the application
    name: Caesar's Management System #name of the application
    group: Caesar James LEE #author or organization of the application