spring:
    application:
        name: caesar-s-management-system

    #MySQL database configuration
    datasource:
        url: jdbc:mysql://localhost:3306/cms_db?allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver

    #JPA and hibernate configuration
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

    #redis configuration
    redis:
        database: 0
        host: localhost
        port: 6379
        lettuce:
            pool:
                max-active: 16  #max total connections
                max-idle: 8     #max idle connections
                max-wait: 3s    #wait 3 second if pool is exhausted
                min-idle: 2     #keep a couple connections alive

    #email sender configuration
    mail:
        host: smtp.gmail.com                            #address of SMTP server
        port: 587
        username: cjl.wannabeafreecitizen@gmail.com     #username of SMTP server
        password: btte yoze tgrk hfbm                   #password of SMTP server
        properties:
            mail:
                smtp:
                    auth: true                          #emable SMTP authentication
                    starttls:
                        enable: true                    #enable STARTTLS cryptography
                    proxy:
                        host: 127.0.0.1
                        port: 7890
        default-encoding: UTF-8
        protocol: smtp

    #remove rabbitMQ and nginx settings for now

    ##rabbitMQ configuration
    #rabbitmq:
        #host: localhost
        #port: 5672
        #username: guest
        #password: guest

    ##file upload configuration
    #servlet:
        #multipart:
            #enabled: true
            #max-file-size: 12MB
            #max-request-size: 18MB

#server configuration
server:
    port: 3002
    #forward-headers-strategy: framework #for Nginx reverse proxy
    servlet:
        session:
            timeout: 30m

#JWT configuration
jwt:
    secret: "Fuck u `Java`!You're so **BLOATED**, **VERBOSE**, and **RIGID**`C++` is **BETTER** than `Java` without any doubtI have loved and will love `C++` since I met `C++11`"
    expiration: 43200000 #12 hours in milliseconds

twilio:
    account-sid:    #twilio account sid
    auth-token:     #twilio auth token
    phone-number:   #twilio from phone